
# Project information
site_name: Zephir Documentation
site_url: https://docs.zephir-lang.com
site_author: Phalcon Team
site_description: >-
  Zephir is an open source, high-level/domain specific language designed to 
  ease the creation and maintainability of extensions for PHP with a focus 
  on type and memory safety.

# Repository
repo_name: zephir-lang/documentation
repo_url: https://github.com/zephir-lang/documentation

# Copyright
copyright: Copyright &copy; 2012 - present Phalcon Team

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate


  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Titillium Web
    code: Source Code Pro
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.svg

# Plugins
plugins:
  - include
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - redirects:
      redirect_maps:
        'index.md': 'introduction.md'

# Hooks
#hooks:
#  - material/overrides/hooks/shortcodes.py
#  - material/overrides/hooks/translations.py

# Additional configuration
extra:
  version:
    default: 0.18
    provider: mike
  annotate:
    json: [ .s2 ]
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zephir-lang

extra_css:
  - assets/css/extra.css

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.extra
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.highlight:
      anchor_linenums: true
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - toc:
      permalink: true

# Page tree
nav:
  - Home:
      - Introduction: introduction.md
      - Why Zephir: motivation.md
      - License: license.md
      - Changelog:
        - Current Version: https://github.com/zephir-lang/zephir/blob/development/CHANGELOG.md
      - Contributing:
        - Contributions: https://github.com/zephir-lang/zephir/blob/development/CONTRIBUTING.md
        - Asking a question: https://github.com/orgs/zephir-lang/discussions
        - Requesting a change: https://github.com/zephir-lang/zephir/issues
        - Issuing a Pull Request: https://github.com/zephir-lang/zephir/pulls
  - Getting Started:
      - Installation: installation.md
      - Tutorial: tutorial.md
  - Core:
    - Basic Syntax: language.md
    - Types: types.md
    - Operators: operators.md
    - Operator Precedence: operator-precedence.md
    - Arrays: arrays.md
    - Classed and Objects: oop.md
    - Built-in methods: builtin-methods.md
    - Control structures: control-structures.md
    - Exceptions: exceptions.md
  - Features:
    - Calling functions: functions.md
    - Closures: closures.md
    - Custom optimizers: optimizers.md
    - Configuration: config.md
    - Command Line: command-line.md
  - Advanced:
    - Lifecycle hooks: lifecycle.md
    - Extension globals: globals.md
    - phpinfo() sections: phpinfo.md
    - Static analysis: static-analysis.md
    - Optimizations: optimizations.md
    - Compiler warnings: warnings.md
